local Stack = require("overlook.stack")

-- Tiny popup factory (just a plain table with the fields Stack inspects)
local function popup(winid)
  return { winid = winid }
end

describe("Stack — basic LIFO", function()
  it("starts empty", function()
    local s = Stack.new()
    assert.is_true(s:empty())
    assert.are.equal(0, s:size())
    assert.is_nil(s:top())
  end)

  it("push/pop maintains LIFO order", function()
    local s = Stack.new()
    local a, b, c = popup(1), popup(2), popup(3)
    s:push(a)
    s:push(b)
    s:push(c)
    assert.are.equal(3, s:size())
    assert.are.equal(c, s:top())
    assert.are.equal(c, s:pop())
    assert.are.equal(b, s:top())
    assert.are.equal(b, s:pop())
    assert.are.equal(a, s:pop())
    assert.is_true(s:empty())
  end)

  it("pop returns nil when stack is empty", function()
    local s = Stack.new()
    assert.is_nil(s:pop())
  end)

  it("push clears trash (new popup invalidates redo history)", function()
    local s = Stack.new()
    s:push(popup(1))
    s:pop() -- trash: [{1}]
    assert.are.equal(1, #s.trash)
    s:push(popup(2)) -- new push -> clear trash
    assert.are.equal(0, #s.trash)
  end)
end)

describe("Stack — trash and restore", function()
  it("pop moves the popup to trash", function()
    local s = Stack.new()
    local a = popup(1)
    s:push(a)
    s:pop()
    assert.are.equal(a, s:peek_trash())
  end)

  it("pop_trash removes and returns the last trash item", function()
    local s = Stack.new()
    local a, b = popup(1), popup(2)
    s:push(a)
    s:push(b) -- build stack: [a, b]
    s:pop()
    s:pop() -- trash: [b, a] (b popped first, then a)
    assert.are.equal(a, s:pop_trash())
    assert.are.equal(b, s:pop_trash())
    assert.is_nil(s:pop_trash())
  end)

  it("restore_item appends to items WITHOUT clearing trash", function()
    local s = Stack.new()
    local a, b = popup(1), popup(2)
    s:push(a)
    s:push(b) -- build stack: [a, b]
    s:pop()
    s:pop() -- trash: [b, a]
    local restored = s:pop_trash() -- pops a; trash: [b]
    s:restore_item(restored) -- items: [a]; trash MUST remain [b]
    assert.are.equal(1, #s.trash)
    assert.are.equal(b, s.trash[1])
    assert.are.equal(a, s:top())
  end)
end)

describe("Stack — remove_by_winid", function()
  it("removes a top item and moves it to trash", function()
    local s = Stack.new()
    s:push(popup(1))
    s:push(popup(2))
    s:push(popup(3))
    local removed = s:remove_by_winid(3)
    assert.are.equal(3, removed.winid)
    assert.are.equal(2, s:size())
    assert.are.equal(2, s:top().winid)
    assert.are.equal(3, s:peek_trash().winid)
  end)

  it("removes a middle item and moves it to trash", function()
    local s = Stack.new()
    s:push(popup(1))
    s:push(popup(2))
    s:push(popup(3))
    local removed = s:remove_by_winid(2)
    assert.are.equal(2, removed.winid)
    assert.are.equal(2, s:size())
    assert.are.equal(1, s.items[1].winid)
    assert.are.equal(3, s.items[2].winid)
    assert.are.equal(2, s:peek_trash().winid)
  end)

  it("returns nil and does not mutate when winid is absent", function()
    local s = Stack.new()
    s:push(popup(1))
    s:push(popup(2))
    assert.is_nil(s:remove_by_winid(999))
    assert.are.equal(2, s:size())
    assert.are.equal(0, #s.trash)
  end)
end)
