name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rev: [nightly, v0.11.1]

    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - name: Run tests
        run: |
          nvim --version
          make test
